[package]
name = "dipper"
version = "0.4.3"
authors = ["not-inept <mason@notinept.me>"]

[dependencies]
serenity = "0.4"
config = "0.6"
coinnect = "*"
bson = "0.10.0"
mongodb = "0.3.7"
serde_json = "*"
chrono = "0.4"
typemap = "0.3.3"
parser = { path ="./parser" }
gnuplot = "0.0.25"
rand = "0.4.2"